name: "Pandora's Box"
version: 1.0.0
description: "An online auction platform for luxury items"
environment:
  - django
  - html
  - css
  - javascript

# Server configuration
server:
  port: 8000
  host: localhost
  static_url: "/static/"
  media_url: "/media/"

# Database configuration (Django)
database:
  engine: "django.db.backends.sqlite3"
  name: "db.sqlite3"
  # For production:
  # engine: "django.db.backends.postgresql"
  # name: "pandoras_box_db"
  # user: "pandora_user"
  # password: "secure_password"
  # host: "localhost"
  # port: 5432

# Authentication settings
auth:
  login_redirect_url: "home"
  logout_redirect_url: "/"
  password_reset_timeout_days: 3

# Application features
features:
  - user_registration
  - item_listing
  - bidding
  - bid_history
  - admin_dashboard
  - subscriber_management

# Auction settings
auction:
  default_bid_increment: 10.00
  auto_extend_minutes: 5
  item_categories:
    - Vehicles
    - Jewelry
    - Art
    - Real Estate
    - Electronics
    - Collectibles

# Email configuration
email:
  backend: "django.core.mail.backends.console.EmailBackend"
  host: "smtp.example.com"
  port: 587
  use_tls: true
  from_address: "noreply@pandorasbox.com"

# Security settings
security:
  debug: true
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
  csrf_trusted_origins: []
  session_cookie_secure: false
