# Generated by Django 5.2 on 2025-04-14 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_item_bid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("open", "Open for Bidding"), ("closed", "Bidding Closed")],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
