name: Update Contributors Graph

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate Contribution Stats
        run: |
          # Create a temporary file for statistics
          echo "# Contribution Statistics" > stats.md
          echo "" >> stats.md
          
          # Add visual contributor images
          echo "## Visual Contribution Chart" >> stats.md
          echo "" >> stats.md
          echo "[![Contributors](https://contrib.rocks/image?repo=${GITHUB_REPOSITORY})](https://github.com/${GITHUB_REPOSITORY}/graphs/contributors)" >> stats.md
          echo "" >> stats.md
          
          # Start building the mermaid pie chart
          echo "## Contribution Breakdown" >> stats.md
          echo "" >> stats.md
          echo '```mermaid' >> stats.md
          echo "pie title Contribution by Author" >> stats.md
          
          # Get list of contributors and their commit counts
          CONTRIBUTORS=$(git log --format='%an' | sort -u)
          
          for contributor in $CONTRIBUTORS; do
            commits=$(git log --author="$contributor" --oneline | wc -l)
            # Add this contributor to the pie chart
            echo "    \"$contributor\": $commits" >> stats.md
          done
          
          # Close the mermaid code block
          echo '```' >> stats.md
          
          # Add timestamp
          echo "" >> stats.md
          echo "Last updated: $(date)" >> stats.md
      
      - name: Update README with Stats
        run: |
          awk '
          BEGIN { p=1 }
          /<!-- CONTRIBUTION-STATS:START -->/ { print; p=0; system("cat stats.md") }
          /<!-- CONTRIBUTION-STATS:END -->/ { p=1; print; next }
          p { print }
          ' README.md > README.md.new
          mv README.md.new README.md
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update contribution charts" || echo "No changes to commit"
          git push
