name: Update Contributors Graph

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history
      
      - name: Generate Contribution Stats
        run: |
          # Create a temporary file for statistics
          echo "# Contribution Statistics" > stats.md
          echo "" >> stats.md
          
          # Add a visual contributor chart
          echo "## Visual Contribution Chart" >> stats.md
          echo "" >> stats.md
          echo "[![Contributors](https://contrib.rocks/image?repo=${GITHUB_REPOSITORY})](https://github.com/${GITHUB_REPOSITORY}/graphs/contributors)" >> stats.md
          echo "" >> stats.md
          
          # Add the table as before
          echo "## Detailed Contributions" >> stats.md
          echo "" >> stats.md
          echo "| Contributor | Commits | Additions | Deletions |" >> stats.md
          echo "|-------------|---------|-----------|-----------|" >> stats.md
          
          # Get list of ALL contributors including those with access listed in GitHub
          CONTRIBUTORS=$(git log --format='%an' | sort -u)
          
          for contributor in $CONTRIBUTORS; do
            commits=$(git log --author="$contributor" --oneline | wc -l)
            additions=$(git log --author="$contributor" --stat | grep -o '[0-9]* insertion' | awk '{s+=$1} END {print s}')
            deletions=$(git log --author="$contributor" --stat | grep -o '[0-9]* deletion' | awk '{s+=$1} END {print s}')
            
            # Handle empty values
            [ -z "$additions" ] && additions=0
            [ -z "$deletions" ] && deletions=0
            
            echo "| $contributor | $commits | $additions | $deletions |" >> stats.md
          done
          
          # Add timestamp
          echo "" >> stats.md
          echo "Last updated: $(date)" >> stats.md
      
      - name: Update README with Stats
        run: |
          awk '
          BEGIN { p=1 }
          /<!-- CONTRIBUTION-STATS:START -->/ { print; p=0; system("cat stats.md") }
          /<!-- CONTRIBUTION-STATS:END -->/ { p=1; print; next }
          p { print }
          ' README.md > README.md.new
          mv README.md.new README.md
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update contribution stats" || echo "No changes to commit"
          git push
